Shivam
kaustubh-karkare/project-omega pull request #46
Opened 2017-11-12 11:36 UTC by Shivam-sopho

Main library in - library.py
Driver Program = test.py

2019-08-17 15:02 UTC, kaustubh-karkare requested changes
- You can use something like https://www.pylint.org/
- The existing comments will result in significant refactoring, so I didn't review in much detail the code inside the Parser file.

2019-08-17 15:02 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +import re
Lets start using Python3, so that you can use specify typehints.

2019-08-17 15:02 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +    printer = library.assignment1()
The filename / class name should be based on what it contains. Instead of "assignment1", call it Parser.

2019-08-17 15:02 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +import library
Write a proper test using the unittest module provided by Python.

2019-08-17 15:02 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        self.userpassnonrequiredargs = {}
Saving the results in the same class makes the class impossible to reuse.
You should split up the results from the parser.

2019-08-17 15:02 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +        key=(1234, "r", "local"), name=("shivam", "nr", "local"))
This API is definitely needs improvement.
Check out how the argparse module works: https://docs.python.org/3/library/argparse.html
What you're trying to do is to create your own simplified version of that.

2019-08-17 15:02 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                self.requiredargs[commands] = self.copyargs[commands]
`self._required_args`

Check out the python style guide for the conventions you need to abide by.
The style guide is mentioned in the instructions for solving the problems here.

2019-08-17 15:02 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +            print("The \"--%s\" argument is required, but missing from input." % command)
Error messages usually go to stderr, not stdout.

2019-08-17 15:02 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        for commands in self.userpassedargs:
Inconsistent indenting. Another thing covered by style guide.

2019-08-18 14:50 UTC, Shivam-sopho commented
@kaustubh-karkare . Taking your suggestions into consideration I have made the changes . 
1. For the python code formatting I am using pep8 in place of pylint
2. I have tried to setup the Unit Test using Unittest module of python

2019-08-18 15:46 UTC, kaustubh-karkare requested changes
Okay, this is better, but still needs work.

2019-08-18 15:46 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +class simple_test(unittest.TestCase):
Class names are typically camelCase, so SimpleTest

2019-08-18 15:46 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +        self.printer = library.parser()
The names here are inconsistent.
Why is a "parser" stored in a variable called "printer"? It'll confuse people.
See point 3 of the [coding instructions](https://github.com/kaustubh-karkare/project-omega/blob/master/assignments/README.md).

2019-08-18 15:46 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +    def test_required_args(self):
These tests are not comprehensive enough yet.
Ie - in order to test_required_args, you need to prove that an exception is raised when the required argument is not provided.

2019-08-18 15:46 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +            self.commands), {'key': 123, 'name': 's'})
Similarly, need to add case for what happens when the expected type (eg - number) != actual type (string like "abc").

2019-08-18 15:46 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +    """
Remove all necessary code.

2019-08-18 15:46 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +    def add_options(self, **wargs):
This variable is conventionally called "kwargs" for "KeyWord ARGumentS".

2019-08-18 15:46 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        Returns:
This method does not have a return statement.

2019-08-18 15:46 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        self.record = store_args_options()
Ah, so this separate class contains the options, both the expected and the value values.
I think you may have misunderstood me: we want a Parser class object which consists of a list of expected values, and then a separate object that contains actual values. Eg - 

```
parser = Parser()
parser.add_option('key', type=int, required=True)
parser.add_option('name', type=str)
self.assertEqual(parser.parse(['--key=123', '--name=abc']), {'key': 123, 'name': 'abc'})
self.assertEqual(parser.parse(['--key=456']), {'key': 456})
```

2019-08-18 15:46 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        if "local" in self.local and "remote" in self.local:
Hardcoding specific values is not allowed!
You must make the configurable as part of your API.

2019-08-18 15:46 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        return self.validateargs()
Why not do the validation while storing the values? It doesn't need to be a separate phase.

2019-08-19 13:10 UTC, Shivam-sopho commented on solutions/assignment1/library.py
> +        return self.validateargs()
If Validation is done in separate phase I thought it may make program more modular. Please let me know if I am heading in wrong direction.

2019-08-19 15:50 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        return self.validateargs()
Ah, a reasonable instinct. The reason I suggested doing both things together is that you kinda have a "single module of everything related to one value" in one place.

2019-08-19 16:56 UTC, Shivam-sopho commented on solutions/assignment1/library.py
> +        self.record = store_args_options()
One thing I have doubt is that In the assignment you have mentioned about local and remote . What does that actually mean.

2019-08-19 17:45 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        self.record = store_args_options()
They're just 2 random options that cant be used together.
Eg - you can either perform the action locally, or remotely.

2019-08-24 17:05 UTC, Shivam-sopho commented on solutions/assignment1/library.py
> +        self.record = store_args_options()
Every time the user passes the command line arguments for parsing, will that we every time treated as new or the last passed arguments will be retained with it ? Suppose the example in which we have called the parser.parse option 2 times.

2019-08-24 19:52 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        self.record = store_args_options()
Each time you call parse, it's a new thing.
You don't have to store values across calls.

2019-08-24 23:35 UTC, Shivam-sopho commented
1. I have taken your suggestions into consideration and made the changes.
2. Changes the API Structure to match the Python Arg Parser Module
3. Refined the UnitTests

2019-08-25 15:37 UTC, kaustubh-karkare requested changes
Much better! Some more refactoring needed, but glad to see the progress!

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +class StoreArgsOptions:
Huh, not sure why you need this class at all, just looks like a straightforward dict.

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        self.record = StoreArgsOptions()
We should not store the results of parsing in the class.
Given the input, we can just parse it, and return the results immediately.

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +            self._expected_args[arg] = kwargs
Interesting, this requires the "application developer" to understand internal details about your library, which is not good. I would recommend explicitly calling our the valid args/kwargs in your signature, so that the signature is enough to understand what is going on. And only allow 1 option to be added at a time.

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        for keys in argslist:
s/keys/key, since it is one item.

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +            keys = keys.split("--")
```
assert key.startswith("--")
name, value = key[2:].partition("=")
```

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                print(self.record.get_user_passed_arg())
Libraries aren't allowed to print stuff unless explicitly allowed :)

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        for commands in self.record.get_user_passed_arg():
Instead of doing each type of check in phases, you can try to do all the checks for a given argument at a time.
Eg - after your splitting operation, you can immediately verify that it is expected, and then do the type checking etc, before adding it to the result dictionary. That way, you avoid all the extra loops :)

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +            try:
Looks like you're just trying to fit it into whatever type it goes in, which is non-ideal.
The specific type should be configurable (check out how the argparse module does it).

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +            typeuserdefined = self._expected_args[commands]['type']
I'm confused what this does, if you don't use it in the previous section.

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        for commands in self.record.get_user_passed_arg():
s/commands/command/

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        if "local" in self.modes and "remote" in self.modes:
Once again, this is hardcoding specific values in your code.
Ie - what if I wanted 5 different pairs of arguments to be mutually exclusive? This currently model would not support that.

How about making mode an arbitrary string, and you just ensure that the corresponding count is not more than one? Also, "mode" isn't the best name, maybe "unique_key" ?

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +            self.record.empty_user_passed_arg()
Given that you reset it at the end anyway, there is no reason to save it on the class in the first place.
It creates an unnecessary restriction that the parser cannot be used across multiple threads.

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +    def errorlisting(self, errorcategory, command):
This is just a library that will be called by a larger application, so you should raise exceptions instead. The caller can then choose to display the errors, or do something else.

I'd also recommend not having a separate method to generate error messages, just create the message from the place where you'd call this. That way, all the relevant logic is in one place.

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +        self.assertEqual(self.parser.parse(self.commands), 'mandatoryerror')
Right now, your function can either return a valid result, or this error string.
This means that all callsites have to check the 2 cases, which is non-ideal.
Throwing exceptions means that whoever is interested can catch them.

2019-08-25 15:37 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +    def test_overflow_args(self):
I think you mean "unexpected" instead of "overflow"?

2019-09-08 15:09 UTC, Shivam-sopho commented
As per suggestions I have made changes in the implementation
1. Make parsing in one pass instead of various passes.
2. Usage of Exceptions
3. Not storing the result of parsing directly returning it.
4. Make corrections in mutually exclusive keys logic.

2019-09-10 01:41 UTC, kaustubh-karkare requested changes

2019-09-10 01:41 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +            self._expected_args[arg] = kwargs
This is still an issue.

2019-09-10 01:41 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                value = x[2]
name, _separator, value = keys[2:].partition('=')

2019-09-10 01:41 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                    self._required_args[keys] = value
You can do this in one line:
```
required_args = set([name for name, value in self._expected_args.items() if "required" in value])
```
Also note that `required_args` is a local variable, it does not need to be a class property, since it is never accessed outside this method.

2019-09-10 01:41 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                        raise ValueError("unexpected")
You can create your own exception types (ParserError) instead of existing ones (ValueError).
Makes it clearer when you write code for try-catch.

2019-09-10 01:41 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                        return str(error)
Wait, you're raising an exception and then immediately catching it? This is equivalent to not raising it at all.
That kinda defeats the point of raising exceptions ... you want to let the application/test code catch it, instead of doing it here.

2019-09-10 01:41 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                    value = int(value)
> Looks like you're just trying to fit it into whatever type it goes in, which is non-ideal.
The specific type should be configurable (check out how the argparse module does it).

2019-09-23 18:11 UTC, Shivam-sopho commented
As per suggestions I have made changes in the implementation
1. Improved the Usage of Exceptions
2. Included which options application programmer can pass
3. Replaced codes with one liners .

2019-09-25 15:57 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +            self.assertEqual(str(error), 'mandatoryerror')
You can do:
```
with self.assertRaisesRegex('mandatoryerror'):
  self.parser.parse(self.commands)
```

2019-09-25 15:57 UTC, kaustubh-karkare commented on solutions/assignment1/test.py
> +        self.parser.add_option('name1', unique_key="local", type=str)
Having to specify a unique_key in every case is inconvenient for users who don't actually care about this.
An easy fix option is to assume a default of None, which means there are no conflicts. That way, you only specify this for the options that care about it.

2019-09-25 15:57 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        self._required_args = {}
Not used anymore.

2019-09-25 15:57 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +            if keys.startswith('--'):
If this isn't true, what happens? You might want to raise an exception.

2019-09-25 15:57 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                    raise ParserError("unexpected")
Okay, so you're using a custom exception, which is progress! You might also want to give detailed error messages in the exceptions, so that it is easy to debug. "unexpected option: <name>"

2019-10-07 18:45 UTC, Shivam-sopho commented
As per your suggestions I have added the changes . Please have a look and let me know if any new changes are required.

2019-10-23 11:50 UTC, kaustubh-karkare requested changes

2019-10-23 11:50 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                typeuserpassed = type(value)
You're still special casing `int` and `float` here.
```
value = self._expected_args[name]['type'](value) # raises ValueError if needed
```

2019-10-23 11:50 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                    previous_unique_key = present_unique_key
This logic depends on the specific ordering, which means that you can circumvent it easily, if you have multiple unique_key values.

2019-10-23 11:50 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +            self._expected_args[arg] = kwargs
I would still highly recommend not using *args & **kwargs unless you're forwarding arguments, since it requires the "application developer" to understand internal details about your library.
```
def add_option(self, name, *, required=true, type=str, unique_key=None):
```
The above will prevent the application developer from making mistakes.

2019-10-23 11:50 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +    def isstring(self, string):
This will not exist in the final form, since this is also a form of special casing for strings, which is not allowed.

2019-10-23 16:52 UTC, Shivam-sopho commented
I have added the changes as per your suggestions. Please have a look on them.

2019-10-24 08:16 UTC, kaustubh-karkare approved these changes
I think at this point, you've completed the goals I had in mind.
There's still some items left to fix in the code, so check out the comments but once you've fixed it, you can close the PR.

2019-10-24 08:16 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                raise ParserError("mandatoryerror")
I would recommend more detailed error messages instead of a single word.
"Missing required argument: {name}"

2019-10-24 08:16 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +        for commands in required_args:
`for name in required_arg_names`

2019-10-24 08:16 UTC, kaustubh-karkare commented on solutions/assignment1/library.py
> +                    raise ParserError("conflict")
I don't think this logic is correct.
If any conflict_checker[uniquekey] == 2, then you have to raise an exception.
uniquekey_count > 1 is allowed, if you're using 2 separate uniquekeys

2019-10-24 14:19 UTC, Shivam-sopho commented
Made the above changes .

2019-10-24 14:19 UTC, closed without merging