Added solution to Command Line Parser with Unit Tests
kaustubh-karkare/project-omega pull request #50
Opened 2019-08-23 05:29 UTC by pranjalrai

I have added solution for assignment 1 along with unit tests. I have used pylint for uniform syntax. Please suggest changes, if required. Thanks.

2019-08-23 11:18 UTC, kaustubh-karkare requested changes

2019-08-23 11:18 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +
You've hardcoded all the expectations, which wasn't the intent :)
This should be configurable, each testcase can set different expectations with the parser.

```
parser = Parser()
parser.add_option('key', type=int, required=True)
parser.add_option('name', type=str)
self.assertEqual(parser.parse(['--key=123', '--name=abc']), {'key': 123, 'name': 'abc'})
self.assertEqual(parser.parse(['--key=456']), {'key': 456})

parser = Parser()
parser.add_option('name', type=str)
try:
  parser.parse(['--key=789'])
catch ArgumentParserException as e:
  self.assertTrue("unrecognized arguments: --key" in e.message)
```

Keep in mind [coding instruction 4.2](https://github.com/kaustubh-karkare/project-omega/blob/master/assignments/README.md):

> Additionally, make sure that your code is resuable: that it solves more than just the exact problem you are working on right now. In real life, requirements are always changing, and you want to make sure you can handle that with minimal effort. To simulate that, I will always evaluate your code at a higher standard than the problem statement given to you.

2019-08-23 11:18 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +    'conflicting_with': LOCAL_COMMAND
https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_mutually_exclusive_group

Can you implement something like this?

2019-08-23 11:18 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +def main(argv):
Lets use some OOPs concepts :)
All this should be in a class.

2019-08-23 11:18 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        if command in ('--local', '--remote'):
You cant hardcode any specific arguments in your logic that is supposed to be general.
Applies to various places below also.

2019-08-23 11:18 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        argument = arg.split('=')
This works. But suggestion:
```
name, value = arg.partition('=')
```

2019-08-23 11:18 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/TestCommandLParser.py
> +class TestCommandLParser(unittest.TestCase):
Good tests!
However I would recommend that your class return proper json objects (not strings), since the actual use of an argument parse is to serve as an input to something else.
Also, if something goes wrong, the class could raise exceptions, allowing the caller to catch them and ignore if needed, instead of having to check what is inside the return value.

2019-08-27 16:34 UTC, pranjalrai reviewed
1. Created a class and encapsulated all the functions inside it.
2. Raised exceptions in a more generalized way.
3. Adding a new command is more generalized now.
4. Added validation through regular expression. Each command doesn't need a separate function to validate its argument.

2019-08-27 21:25 UTC, kaustubh-karkare requested changes
Excellent progress!

2019-09-02 04:33 UTC, pranjalrai reviewed
1. Separated the previous __init__ and get_arguments methods in 2 different classes.
2. COMMANDS is now being accessed using self.COMMANDS in CommandLineParser class.
3. Added a generalized implementation for flag variables/commands.

Please review the changes.

2019-09-05 13:45 UTC, pranjalrai reviewed
Created a separate main file that will control/call the application logic of Command-Line Parser and the unit test file.
Please review the changes.

2019-09-06 12:54 UTC, kaustubh-karkare requested changes

2019-09-06 12:54 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        self.COMMANDS[self.command_name] = self
I don't think you need to have static properties like this.
Why? Because I'd like to be able to create separate `CommandLineParser` objects, each with a separate list of valid options.

2019-09-06 12:54 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        self.COMMANDS = super().COMMANDS
all caps variable names are usually reserved for constants, so here, I would just call it "self.commands" (lower case).

2019-09-06 12:54 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        final_response = error_message
Instead of returning an error message, you should raise an exception, so that the application/testing layer can catch it and do whatever it wants with it (print it and exit, or log it and exit, or use some default fallback behavior).
Parsing a string return value (which is what this method generates) is more inconvenient. The API should be: the method either returns a Dict, or raises an exception.

2019-09-06 12:54 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/TestCommandLParser.py
> +        print(type(result))
You can remove all these random print statements in your code, once you're done running it manually.

2019-09-06 12:54 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/main.py
> +    TEST.TestCommandLParser().call_functions()
This shouldn't be here, and the call_functions method shouldn't need to exist. The unit testing file is independent.

https://docs.python.org/3.6/library/unittest.html#unittest.main

2019-09-06 12:54 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        self.is_local = is_local
Based on your usage of this, I think `is_flag` is a better name.
The existence (or non-existence) of the option is equivalent to whether the flag is set or not set.

2019-09-06 12:54 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/main.py
> +REMOTE_COMMAND = CLP.AddCommand('--remote', None, r'/\A\z/', None, '--local', True)
Instead of calling a separate method, you should just make it an API on your parser object.
```
parser = CLP.CommandLineParser()
parser.add_command(...)
parser. get_arguments(sys.argv)
```

2019-09-07 06:37 UTC, pranjalrai reviewed
1. Removed static dictionary 'command'. Each Command-Line Parser object will have its own command dictionary.
2. is_local -> is_flag
3. Separated test file.
4. If something goes wrong, instead of returning a string, now raising an exception.
5. Removed print statements.
6. Replaced uppercase variable names.

Please review the changes.

2019-09-10 01:22 UTC, kaustubh-karkare requested changes

2019-09-10 01:22 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +                print(exception)
Btw, there are still print statements left in here.

2019-09-10 01:22 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +            final_response = json.dumps(results, sort_keys=True)
Returning a `dict` is more useful than returning a string.

2019-09-10 01:22 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        commands[self.command_name] = self
This class shouldn't be responsible for populating the dict. Instead, the `CommandLineParser` class should be the one to create the dict, and add items to it. It will result in a much better API ... check out how python's argparse module is supposed to be used.

2019-09-10 01:22 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +            """some error occurred already"""
If you raise an exception as soon as you found a problem, you wouldn't need to do this type of check at all.

2019-09-10 01:22 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +                if required_command is not None and required_command not in commands_found:
I'm not sure that your "required_command" check works as intended.
Shouldn't you be looping over `self.commands` instead of commands_found?

2019-09-10 05:00 UTC, pranjalrai commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +                print(exception)
This print statement was intended to let the user know about the exception raised. Should I remove this print statement?

2019-09-10 05:02 UTC, pranjalrai commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +                if required_command is not None and required_command not in commands_found:
Actually commands_found contains all the commands received from the user in command line input, so we need to check if a required command is present in the list or not.

2019-09-10 15:26 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        command = {'command_name': command_name, 'format': format, 'required_command': required_command, 'conflicting_command': conflicting_command, 'is_flag': is_flag}
Saving complex data in dictionaries makes it harder to perform typechecking, so the usual recommendation is to prefer storing it in a class.
```
command = Command(name=name, format=format, ...)
self.commands[command.name] = command
```
Note that `self.commands` is a dict, to avoid the O(n) complexity of your search_command method.

2019-09-10 15:26 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        commands_found = []
Instead of a list, a set is more appropriate, right?

2019-09-10 15:26 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +                error_message = 'invalid number of arguments passed to ' + argument[0]
raise Exception('invalid number of arguments passed to ' + argument[0])

2019-09-10 15:26 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +            if required_command is not None and required_command not in commands_found:
This is still the pairwise requirements. Lets just simplify and do individual requirements.
So required=True means that if it is missing from input, you raise an exception.

2019-09-10 15:26 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        final_response = json.dumps(results, sort_keys=True)
The library should either returns a dict (instead of a string), or raise an exception (instead of returning it).

2019-09-10 15:26 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/TestCommandLParser.py
> +class TestCommandLParser(unittest.TestCase):
^

2019-09-10 17:46 UTC, kaustubh-karkare approved these changes

2019-09-10 17:46 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +                    raise Exception(command + ' is not a recognized command')
extra indent

2019-09-10 17:46 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +            if command not in self.commands: # commands with at least one argument
Not sure what the comment means.

2019-09-10 17:46 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/CommandLineParser.py
> +        return {'final_response': final_response}
I was suggesting that instead of:
```
final_response = json.dumps(results, sort_keys=True)
return {'final_response': final_response}
```
You could just do:
```
return final_response
```

2019-09-10 17:50 UTC, kaustubh-karkare requested changes
Unit test needs to be updated.

2019-09-10 18:52 UTC, kaustubh-karkare approved these changes

2019-09-10 18:52 UTC, kaustubh-karkare commented on solutions/Pranjal Rai/src/Assignment 1/TestCommandLParser.py
> +            parser.get_arguments(command_line_param)
You might as well have done:
```
parser.get_arguments(['./test', '--key=1a3', '--name=pranjal'])
```

2019-10-11 14:43 UTC, closed without merging

2019-10-23 12:02 UTC, kaustubh-karkare commented
Use separate branch for different problems. The code for build automation tool should not have appeared here.