Solution added for 2nd Assignment
kaustubh-karkare/project-omega pull request #59
Opened 2019-09-06 11:04 UTC by AbhiTaker

2019-09-06 13:48 UTC, kaustubh-karkare requested changes
You can start working on part2 also now.

2019-09-06 13:48 UTC, kaustubh-karkare commented on solutions/abhitaker/build/src/make/make.go
> +type PhaseNode struct {
In our care, we call these "BuildRules".

2019-09-06 13:48 UTC, kaustubh-karkare commented on solutions/abhitaker/build/src/make/make.go
> +	filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
Instead of assuming that the current directory is the location, can you make this configurable?
```
build --root=./test_dir/ clean run
```

2019-09-06 13:48 UTC, kaustubh-karkare commented on solutions/abhitaker/build/src/make/make.go
> +		if fileName == "build.json" {
Put this "build.json" in a constant, instead of a random string in the middle of the code.
That is also something that could be made configurable.

2019-09-06 13:48 UTC, kaustubh-karkare commented on solutions/abhitaker/build/src/make/make.go
> +		for id2 := 0; id2 < len(phases); id2++ {
You can avoid this loop if you use a map right?

2019-09-06 13:48 UTC, kaustubh-karkare commented on solutions/abhitaker/build/src/make/make_test.go
> +
The testing here is inadequate.
You want to show that the entire system works as a whole too, and cover failure cases, etc.

2019-09-12 04:09 UTC, AbhiTaker commented
The Graph Search Function is implemented twice for the sake of segregation.

4 CLI options are provided :
-  **--root**: Location of Directory  to run make
-  **--buildfile**: Name of the Build File
-  **--wait-time**: Duration before checking for modified files
-  **--watch**: To enable the watch feature

2019-10-23 12:54 UTC, kaustubh-karkare requested changes
I was having a hard time reviewing this, since your Main file is doing too many things (and also, I'm not fluent in the language).

You should split them into smaller modular pieces (one for build rule related logic, another for depth first execution, another for file update detection, etc), each of which are independently reviewable, and have clean apis that I can assume to be a black box (ie - don't need to understand the details of a one file, while trying to understand a different file).

2019-10-23 12:54 UTC, kaustubh-karkare commented on solutions/abhitaker/build/src/main/main.go
> +	flag.IntVar(& waitTime, "wait-time", 60, "Name of the Build file name")
Copy paste error for description.

2019-10-23 12:54 UTC, kaustubh-karkare commented on solutions/abhitaker/build/src/make/make.go
> +		file := strings.Split(path, "/")
Ummm ... "file" is not a good name for the contents of this variable.

2019-10-23 12:54 UTC, kaustubh-karkare commented on solutions/abhitaker/build/src/make/make.go
> +func ParseJSON(path, buildFilename string) ([]BuildRule, error) {
The name "ParseJSON" is very generic, and does not indicate that we're dealing with JSONbuildRuleData.

2019-10-23 12:54 UTC, kaustubh-karkare commented on solutions/abhitaker/build/src/make/make.go
> +func DepthFirstSearch(root string, currentBuildNode NodeState, nodeMap map[string]NodeState) ([]string, error) {
This is not a search. This is a traversal.

2020-07-21 05:07 UTC, closed without merging