Assignment 2.1: Build Automation Tool
kaustubh-karkare/project-omega pull request #60
Opened 2019-09-09 21:57 UTC by ankurdubey521

So midway through I decided I wanted to do this assignment in Python, mainly because 
1) my skills in python are quite rusty and based on a lot of googling
2) was having quite a lot of trouble with setting up execSync in node
I therefore request you to be stricter with your analysis of the code

2019-09-10 02:10 UTC, kaustubh-karkare requested changes

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/.idea/Build Automation Tool.iml
> +<?xml version="1.0" encoding="UTF-8"?>
All these xml files should not be part of your PR. Add them to your .gitignore file, since they are relevant only for you.

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_buildconfig.py
> +        json_path = 'json/test1.json'
The input to your BuildConfig class should be a directory, not a specific file.
The file name "build.json" is fixed, so "test1.json" violates that pattern.

You can add the "build.json" suffix in the BuildConfig class, instead of relying on the caller to add it.

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_buildconfig.py
> +        self.assertEqual(config.command('clean'), "rm -f test.o && rm -f test.exe")
Interesting, these utility methods can definitely be useful, but I'd recommend better naming here.
In this case, adding a "get_" prefix to all of them will make it clear that these are not "set_" or "has_" or "check_" or whatever else methods.

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_builder.py
> +        path = '/home/ankurdubey/Code/Github/project-omega/solutions' \
This path is non-transferrable. If I downloaded this code in my machine, this test would fail, which is bad.

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +        json_file.close()
You should use something like:
```
with open(json_path) as file_handle:
  _ = json.load(file_handle)
```

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +        self._command = {}
Proper naming is important:
* _command suggests a single item.
* _commands suggests a list of items.
* I would use `self.name_to_command` because it looks like a map.

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +        return self._command[command_name]['files']
Create a `Command` class, and then move these getters there.
That will leave you with a single getter here: "get_command(name)"

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/commandrunner.py
> +if __name__ == '__main__':
This section does nothing. Remove it.

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/main.py
> +        deps = config.deps(command)
What if I wanted to run "build algorithms/sort_bubble"?
Since that is not in the current directory, this code would not find it (even though you have the relative path).

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/main.py
> +            except ValueError:
ValueError can be generated by so many things that I have no idea when this will happen. Maybe you want to use a more specific exception?

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_commandrunner.py
> +    unittest.main()
You have tests for the individual components, but not for the overall system (ie - an "integration test").

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_commandrunner.py
> +        exit_code = run(command, print_command=False, cwd='/')
> print_command=False

This should be a default argument value.

2019-09-10 02:10 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/main.py
> +                execute(dep_command, dep_containing_folder_path)
You need to add checks for circular dependencies.

2019-09-11 19:12 UTC, kaustubh-karkare requested changes
Nice!

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +            return Command(name=name, command_string=command_string, deps=deps, files=files)
Instead of creating a Command object on demand, why not do all this in your __init__ method, so that it only needs to be done once?

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +            self._hasFiles = False
Do you really a separate variable for _hasFiles? Why not just check if _files is None? In languages like C++, where a list variable cannot be null, this makes more sense, but not sure it is needed in python.

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +        raise Command.NoDependenciesException("No Dependencies for {}".format(self._name))
I don't even think you need to raise exceptions like this. Ie - if deps aren't specified, the default meaning is that there are no deps, so you can just return an empty list.

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +            raise BuildConfig.UnknownCommandException('No such command "{}" found.'.format(command_name))
I liked this model of associating exceptions with class. Hadn't seen it before somehow.

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/main.py
> +                print("Executing {} dependencies for {} in {}...".format(len(deps), command_name, command_dir_abs))
This doesn't look too useful, since it doesn't include dependencies.
Can we make the dry_run mode print out all the rules/commands it would have executed?
Output like:
```
> build run --dry-run
[algorithms/sort_bubble] g++ -c sort_bubble.cpp
[algorithms/sort_merge] g++ -c sort_merge.cpp
[algorithms/sort_quick] g++ -c sort_quick.cpp
[test] g++ -std=c++11 -c test.cpp
[run] g++ algorithms/sort_bubble.o algorithms/sort_merge.o algorithms/sort_quick.o test.o -o test.exe && ./test.exe
```

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/main.py
> +                self._build_rule_handler(dep_name, dep_dir_abs, root_dir_abs, dry_run)
Given that your `root_dir_abs` is passed around unchanged, why not save it as a class variable?
Also, you can make it configurable: `build run --root-dir ~/project/`

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/main.py
> +if __name__ == '__main__':
It might still be useful to keep this __main__ application logic in a separate file from your library.
I'd also recommend catching your exceptions and only showing the message, instead of the whole stack trace.

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/commandrunner.py
> +def run(command_string, cwd, print_command=False):
I'd just make this a method in your Builder class below.

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_buildconfig.py
> +    def setUpClass(cls):
Alternatively,
```
def setUp(self):
  self.config = BuildConfig('json')
```
avoids dealing with class level stuff.

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_builder.py
> +        path = os.getcwd() + '/test_builder_files/test_compilation_basic'
This assumes that you're in a very specific directory.
Maybe something like https://stackoverflow.com/questions/5137497/find-current-directory-and-files-directory makes it possible to run a test from any location?

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_builder.py
> +        builder.execute_build_rule('clean', path, os.getcwd())
Verify that test.out is deleted.

2019-09-11 19:12 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_builder.py
> +        self.assertEqual(False, os.path.isfile(output_file_path))
self.assertFalse(

2019-10-04 02:04 UTC, kaustubh-karkare requested changes
Excellent progress!

Now for the final requirement: Use multithreading to execute dependency build rules in parallel when possible. And demonstrate the performance benefit via a test, possibly using sleep commands in the command string.

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/.gitignore
> +.idea
btw, it is possible to add .gitignore here to exclude this file too.

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +    def __init__(self, *, name: str, command_string: str, deps: List[str] = None, files: List[str] = None) -> None:
Given the non-intuitive distinction between `Command` and `command_string`, call the class `BuildRule`?

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +        raise Command.NoDependenciesException("No Dependencies for {}".format(self._name))
^ What do you think of this?

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/builder.py
> +            self._root_dir_abs = self._root_dir_abs[:-1]
I usually prefer to do this validation once at the beginning, instead of during every call to this method.

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/file_watcher.py
> +        for file in file_list:
Slightly more descriptive variable name:
```
for file_path in file_list:
```

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/file_watcher.py
> +                print("Detected change of file. Executing command...")
Hmm. How does this method know what we're doing ("Executing command ...") if the function is defined as generic? Access to that information broke an abstraction boundary, right?

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/main.py
> +        root_dir = root_dir[:-1]
Huh, if you already did this check here, why did you need to do it in the other file?

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/main.py
> +            file_list = BuildConfig(path).get_command(command).get_files()
So now you know why the example json included information about files :)
However, should we be including the files for dependencies of the specified rule too?

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_builder.py
> +        path = os.getcwd() + '/test_builder_files/test_compilation_basic'
Interesting, you addressed this concern, but in a way that I didn't expect.

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_file_watcher.py
> +        with open(output_file, 'w') as file:
s/file/file_handle/

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_file_watcher.py
> +    def test_copy_file_on_file_change(self):
Interesting, this proves that your file watcher works.
I'm wondering if there is value in demonstrating that actual build commands also work as expected.

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_file_watcher.py
> +        process = Process(target=file_watcher.watch_and_execute, args=([input_file], copy_file, input_file, output_file))
Interesting, you're using a separate process here.

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/builder.py
> +    def __init__(self):
The way you're using this, the constructor must be followed by a call to execute_build_rule. That kind of expectation is unexpected, and while in theory, you could explain it in documentation, there is a better way:

Make execute_build_rule a @classmethod, which creates the object, and then calls _build_rule_handler too. That way, you only need to call one method from outside this file.

2019-10-04 02:04 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/file_watcher.py
> +        file_edit_times = self._get_file_edit_times(file_list)
You are making an assumption here that the file list is fixed, which IMO we can avoid.
Ie - if you re-explore the build-rule-graph each time, you can detect and appropriately handle changes to the build.json files too. Yes, it is costlier (so I guess you can make it configurable) but might be more useful too, right?

2019-10-08 23:41 UTC, kaustubh-karkare requested changes
Cool, I'm pretty happy with the overall state of things, we're almost done.

My comments are now primarily to clean up inconsistencies, improve readability (stuff that was affecting the overall score) and a couple of minor extensions for learning purposes.

Btw, I tend to unashamedly ask for naming changes that span multiple files. Because if you have good tests, even large refactors should be cheap and safe.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/algorithms.py
> +                visited[dest_node] = False
So a node might appear on the right side (of the dict, ie - inside the list), but not the left? Hmm.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/algorithms.py
> +                raise TopologicalSort.GraphContainsCycleException()
It would be helpful for this exception to also contain the names of the specific build rules that form the cycle.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +        self._command_string = command_string
Now you can just call this `self._command` :)

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +            self._raw_json = json.load(file_handle)
I don't think you need to actually save this on the object.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +        self._name_to_command_object = {}
self._name_to_build_rule

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +                deps = command_entry['deps']
raw_build_rule.get('deps', [])

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +    def get_command(self, command_name: str) -> BuildRule:
get_build_rule

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/file_watcher.py
> +    def watch_and_execute(file_list: List[str], function: Callable[[any], any], *args: any) -> None:
Btw, `Any` typehints are generally not considered useful, and can cause you to miss issues.
In this case, you could declare that this callable takes no arguments (because this method does not provide any) and returns nothing (because this method does not look at the return value) and force the caller to wrap the method in such a function, so that it is clear on the other side too, and the arguments/return-value have no significance here.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/file_watcher.py
> +        print("Listening for changes on {}...".format(file_list))
Instead of printing to stdout directly, you can send these messages to a [logger](https://docs.python.org/3.6/library/logging.html) object, provided in the constructor, and shared across your codebase. That way, if I import your code as a library, I can just point the logger object to write to a file or something.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +        # List of (dependency_name, dependency_dir_abs) for each build rule
A bit nitpicky (so feel free to ignore), but I like to put the more general item first, and then increase specificity.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +        self._dependency_topological_sort = TopologicalSort.sort(self._dependency_graph)
self._topologically_sorted_build_rule_names

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +        if not watch_for_file_changes:
Negative conditions are a bit harder to read / reason about, especially if you're trying to debug something in a stressful situation, and you end up encountering double/triple negatives. And so `if watch_for_file_changes: ...`

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +            self._dependency_topological_sort.append((command_name, command_dir_abs))
I'm generally uncomfortable with special casing, which is what this is.
I would modify the code appropriately so that this situation never happens.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +                dep_dir_abs, dep_name = dep_dir_abs.rsplit('/', 1)
- I guess this is why buck's build rules are like "//path/to/some:rule_name", so that you can do full_rule_name.partition(":"), and there's no ambiguity between the directory path and rule name.
- While I have no strong objections to using tuples like you are, I probably would have gone with strings since they (subjective opinion warning) "feel more elegant".

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +        with ThreadPoolExecutor(max_workers=self._max_threads) as executor:
I see you ended up using multithreading, because subprocess.Popen.wait is blocking. As a learning exercise, would you want to use  to see if you can avoid using multithreading entirely? I imagine you have a list of Popen objects, and you just loop over all of them, using the `poll` method to see if a given one is completed.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +                exit(-1)
Does the `exit` here terminate the thread or the process?
Is it better to just return from here, and allow existing parallel commands to complete properly (but not start any new ones), instead of aborting them?

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/main.py
> +        root_dir = os.getcwd()
Alternatively,
```
current_path = os.getcwd()
root_dir = None
while current_path != root:
  if os.path.exists(current_path + os.path.sep + ".buildconfig"):
    root_dir = current_path
  current_path = parent_of(current_path)
if root_dir is None:
  raise Exception("could not find project root")
```

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_buildconfig.py
> +                     ',{"name":"test","files":["test.cpp"],"command":"g++ -std=c++11 -c test.cpp"}]'
You want your tests to be easily readable too. These long strings are not.
I would do something like:
```
json_string = json.dumps({
  # well formatted data
})

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_buildconfig.py
> +            self.config = BuildConfig(tmpdir)
I guess this reveals the weakness of this API: you're forced to create a temporary file to create these objects.
Could be avoided if your constructor takes in the raw json string, and then you have a @classmethod that loads it from the file and returns an instance, if that is how you want to create it.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_file_watcher.py
> +            process = Process(target=file_watcher.watch_and_execute,
Any reason to prefer multiprocessing over multithreading?

My theory about the current implementation is: your watcher class doesn't have a stop_watching() method, and so `process.terminate()` is convenient.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_file_watcher.py
> +                file_handle.write("Hello World 1.0")
Why do you have to reset this?

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +            self.assertEqual(correct_dependency_graph, dependency_graph)
Yeah, there's no way for me to understand this test without looking at multiple files, which is inconvenient. And because I'm lazy, I'm not motivated to go look at all the file contents, and validate them against the contents of this test here, which means that only 1 human has verified this stuff.

If I have access to an explorer-style view of your codebase, I guess that is easy, so I assume that is why you prefer it. But the PR page that I'm reviewing it in, it isn't easy to figure out. As a result, I have much stronger preference for having all the information in one place.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +            pprint.pprint(dependency_graph, indent=4)
Fine for debugging, but you wouldn't want this if you're running thousands of tests in parallel, which is what happens in large codebases. All the outputs will interfere with each other, and most people running the tests wont even understand the output.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +            sleep(16)
This is the only example that I checked the file contents for, because without that, I couldn't see where the number 16 came from.

2019-10-08 23:41 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/buildconfig.py
> +"""" Sample build.json
This is an fairly detailed and specific example. Better suited for a readme file?

2019-10-09 09:02 UTC, ankurdubey521 commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/algorithms.py
> +                raise TopologicalSort.GraphContainsCycleException()
I intended this to be a generic method.
I have implemented the requested functionality in parallel_builder.py, line 88

2019-10-09 20:52 UTC, ankurdubey521 commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_file_watcher.py
> +            process = Process(target=file_watcher.watch_and_execute,
That's true

2019-10-10 03:49 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/algorithms.py
> +                raise TopologicalSort.GraphContainsCycleException()
Yeah, that's reasonable enough.

2019-10-22 14:30 UTC, kaustubh-karkare requested changes

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/algorithms.py
> +                    if not visited[dest_node]:
I was thinking about this line for a while ... trying to figure out when it will be false. Can you help me out?

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/file_watcher.py
> +logger.addHandler(logging.NullHandler())
Instead of creating separate logger objects for each file, I think you should be passing around a single one (provided to each class as part of its constructor). That way, you only need to configure it once from your "application section" of the code.

The current setup is not thread-safe: ie - I'm trying to run multiple instances of your ParallelBuilder class for whatever reason in parallel, and I want their output to go to different destinations, that isn't possible.

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +            self._root_dir_abs = self._root_dir_abs[:-1]
Can we move this to the constructor now?

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +        command = config.get_build_rule(command_name)
Based on the usage, s/command_name/build_rule_name/

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +            self._dependency_list[dependent_tuple].append(dependency_tuple)
These names "_dependency_graph" and "_dependency_list" are not intuitive: there's no way I'd figure out what is contained in them based on purely the name and, it is very easy to confuse between them.

Something like "_rule_name_to_dependency_rule_names" and "_rule_name_to_dependent_rule_names" makes it easier to figure out, although "rule_name" isn't right since you're using a tuple. I couldn't think of a better name while reviewing, but you get the point.

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +        self._explore_and_build_dependency_graph(command_name, command_dir_abs)
Wait, so in your "execute" method, you called "_explore_and_build_dependency_graph" and then "_execute_build_rule_and_dependencies". So why do you need to call this again?

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +            self._topologically_sorted_build_rule_names.append((command_name, command_dir_abs))
When does this happen?

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +        with ThreadPoolExecutor(max_workers=self._max_threads) as executor:
^ Afaict, this is still pending.
If you write your own polling mechanism, I expect you shouldn't need to use the multithreading module or this ThreadPoolExecutor at all.

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +                        BuildConfig.load_from_build_directory(rule_dir_abs).get_build_rule(rule_name).get_command()
Hmm, as part of the exploration phase, you've already loaded data from files (which is a relatively slow operation I would think), so you should avoid loading the same data again here. Maybe maintain a "self._name_to_build_rule" mapping, that is populated once, and then used here.

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_buildconfig.py
> +        self.config = BuildConfig(json_string)
If you make BuildConfig take in a JSON object, you don't need to serialize it here :)

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_file_watcher.py
> +logger.addHandler(error_handler)
Yeah, this is ... non-ideal.

If this is reasonable default behavior, how about moving this to your main code?
```
parallel_builder = ParallelBuilder(path, MAX_THREAD_COUNT)
# either this ...
parallel_builder.setLogger(logger)
# or this ...
parallel_builder.setDefaultLogger()
```
That way, you avoid this duplication in your tests.

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +        exit_code = ParallelBuilder._run_shell(command, cwd=os.getcwd()).wait()
Calling out how the method name "_run_shell" does not indicate that you're returning a Popen object, so without reading the implementation, I have no idea what you're calling `wait` on.

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +            write_test_files(self._testMethodName, path)
Okay, so you've moved the file structure into the test file, which is progress.
But in the interest of readability, why not keep that test structure right here too?
That way, I don't have to scroll up to find out what this file structure is.

I know this kind of thing is annoying, but the point I'm trying to make is that you always want to optimize for readability, not easy of writing (since people are going to read your code many many more times than you write it).

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +                    dependency_graph[node_tuple[0]].append(item[0])
You cant just use `parallel_builder._dependency_graph` ?

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +            print(toposort)
Once you're done testing, remove print statements :)

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +        return self._last_build_passed
Is this primarily for testing?

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +            parallel_builder = ParallelBuilder(path, MAX_THREAD_COUNT)
Looks like these 4 lines are common across all your tests. How about using the `setUp` and `tearDown` methods to avoid the duplication?

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +            parallel_builder = ParallelBuilder(path, MAX_THREAD_COUNT)
You cant reuse the existing ParallelBuilder object?

2019-10-22 14:30 UTC, kaustubh-karkare commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +            parallel_builder._explore_and_build_dependency_graph('Z', path)
Alternative **optional** design suggestion: instead of having to call this manually, how about doing it from the ParallelBuilder constructor? Instead of exploring dependencies for a single rule, it creates the graph for everything under that directory (not specific to any rule, because that isn't actually needed), and then you can choose to execute a single rule (for which the information is now already cached).

2019-10-30 22:35 UTC, ankurdubey521 commented on solutions/ankurdubey521/Build Automation Tool/Builder/tests/test_parallel_builder.py
> +            parallel_builder = ParallelBuilder(path, MAX_THREAD_COUNT)
fixed

2019-10-30 22:35 UTC, ankurdubey521 commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +        return self._last_build_passed
yes

2019-10-30 22:36 UTC, ankurdubey521 commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +        self._explore_and_build_dependency_graph(command_name, command_dir_abs)
fixed

2019-10-30 22:36 UTC, ankurdubey521 commented on solutions/ankurdubey521/Build Automation Tool/Builder/lib/parallel_builder.py
> +            self._topologically_sorted_build_rule_names.append((command_name, command_dir_abs))
when a rule has no dependency, the dependency graph will contain no edge, thus it's adjacency list would be empty

2019-11-03 09:02 UTC, kaustubh-karkare approved these changes
Cool, this is sufficiently close to the end goal I had in mind. As always, there is more that can be done, but I'm going to approve, since I understand that it can be boring to keep working on the same problem for so long.

2019-11-03 11:07 UTC, closed without merging