assignment-1 solution
kaustubh-karkare/project-omega pull request #61
Opened 2019-09-15 15:10 UTC by drs-11

2019-09-16 00:00 UTC, kaustubh-karkare requested changes

2019-09-16 00:00 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +    def add_argument(self, arg_name, arg_type, cant_be_used_with=[], required=False):
Instead of duplicating all the argument names, you could just use `def add_argument(self, *args, **kwargs):`

2019-09-16 00:00 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +        arguments = sys.argv[1:]
Take this as an argument, so that you can provide whatever value you want as part of tests.
And if not provided, then you can default to this.

2019-09-16 00:00 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +                arg, value = argument.split('=')
* What if there are more/less parts?
* Check out the partition method on strings too.
* A slightly better set of variable names is "name, value", because args refers to the objects and not strings, right?

2019-09-16 00:00 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +                value = int(value) if value.isdigit() else value        #typecasting integer value if string
Only cast to int if the type is int. Because sometimes people might want to put only numbers in a string field too.

2019-09-16 00:00 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +                    raise NoSuchArgError(arg)
This part looks duplicated.

2019-09-16 00:00 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +        self.cant_be_used_with = cant_be_used_with
What if I wanted to enforce that exactly 1 of 5 different arguments is used?
Ie - in this model, I would have to mention the other 4 arguments in each case, which gets tedious.
Also, how do I enforce that exactly one is present?

2019-09-16 00:00 UTC, kaustubh-karkare commented on solutions/assignment-1/test_runs.md
> +# Test runs:
Cool, this is a decent start, but yeah, we need to use a proper framework for testing.
https://docs.python.org/3/library/unittest.html

2019-09-16 00:00 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +        self.value = None
You shouldn't store the values in here.
Create a dict in your `parse_arguments` method and return that.

2019-10-22 15:56 UTC, drs-11 commented
added solution for assignment-2

2019-10-23 12:17 UTC, kaustubh-karkare requested changes
The solution for assignment 2 should be a separate branch/pull-request. I cant review it here, since I don't want to mix the history of comments for 2 problems. I will take a proper look once you separate them :)

2019-10-25 06:46 UTC, kaustubh-karkare commented
This is still pending.

2019-10-25 14:42 UTC, drs-11 commented
will solve them ASAP

2019-10-26 15:21 UTC, drs-11 commented on solutions/assignment-1/CLIparser.py
> +        self.value = None
If I use a dictionary for storing values in that method then the class Argument will become useless. So should I remove the class as well then?

2019-10-28 09:04 UTC, drs-11 commented
changes done

2019-10-29 06:35 UTC, kaustubh-karkare requested changes
We need to fix a bunch of special casing in this code.

2019-10-29 06:35 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +        self.args[arg_name]["required"] = False
Why should these 3 things be special-cased and then everything is also valid?
Instead, you should explicitly define which properties are valid:

```
def add_argument(self, arg_name, *, required=True, <name>=<default>):
```

That way, you only allow users to specify valid things.

2019-10-29 06:35 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +        if self.test:
This is special casing: the Parser class should not be aware of whether it is used in a test or in real.
Instead, you can change the signature to `def parse_arguments(self, argv=None)`, and if argv = None, fallback to sys.argv

2019-10-29 06:35 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +                pass
This is more special casing: we want to be able to support arbitrary types, but here, you only support these 2.
Instead, you can do: `value = self.args[name]["type"](value)`
where the user provides a `type` method that validates whatever the type is, and the value does not comply, raises a ValueError.

2019-10-29 06:35 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +            self.args[name]["used"] = True
Don't save this stuff on the class. It is only relevant in this method, and so save it as a local variable, and then return it.

2019-10-29 06:35 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +                    for other_arg in self.args[arg]["cant_be_used_with"]:
This model has a problem: fields that cannot be used together are called "mutually exclusive". If you have 2 such fields, each field name is mentioned twice (so 4 times in total). If you have 5 such field names (ie - cant_be_used_with contains 4 items), each field name is mentioned 5 times (and so 25 times in total).
This is not good, it makes it hard to manage large groups of mutually exclusive fields.

2019-10-29 06:35 UTC, kaustubh-karkare commented on solutions/assignment-1/test.py
> +parser.add_argument('name', str)
Use keyword arguments when possible:
```
parser.add_argument('name', type=str)
```

2019-10-29 06:35 UTC, kaustubh-karkare commented on solutions/assignment-1/test.py
> +args = parser.args
The user of the library should deal with a very simple API, doing as little work as possible.
```
args = parser.parse_arguments()
print(json.dumps(args))
```

2019-10-29 06:35 UTC, kaustubh-karkare commented on solutions/assignment-1/test_runs.md
> +# Test runs:
^ This comment still applies.

2019-11-12 21:36 UTC, kaustubh-karkare requested changes
Good progress, almost done!

2019-11-12 21:36 UTC, kaustubh-karkare commented on solutions/assignment-1/unittest_CLIparser.py
> +        self.assertEqual(parser.parse_arguments(["--key=12345", "--name=drs"]), (eval('{"key": 12345, "name":"drs"}')))
You don't need to eval the string.
```
eval('{"key": 12345, "name":"drs"}') == {"key": 12345, "name":"drs"}  # true
```

2019-11-12 21:36 UTC, kaustubh-karkare commented on solutions/assignment-1/unittest_CLIparser.py
> +import v3
What is v3?

2019-11-12 21:36 UTC, kaustubh-karkare commented on solutions/assignment-1/unittest_CLIparser.py
> +        parser.add_argument('remote', type=None, mutually_exclusive_arg=True)
You should support multiple groups of mutually exclusive arguments :)
So --local and --remote are one group, and additionally --ip-address and --domain-name could be another group.

2019-11-12 21:36 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +            self.args[arg_name][name] = value
What is the value of this?

2019-11-12 21:36 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +                pass
What are these used for?

2019-11-12 21:36 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +                if not isinstance(value, self.args[name]["type"]):
What happens if `self.args[name]["type"]` is a custom function?

2019-11-12 21:36 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +            self.args[name]["used"] = True
^ Pending. This is the main reason for RC :)

2019-11-20 21:06 UTC, kaustubh-karkare approved these changes

2019-11-20 21:06 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +            self.args[arg_name][attribute_name] = attribute_value
Given that you will never use these additional attributes, why even allow them?

2019-11-20 21:06 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +            except TypeError:        #to catch None calling as a function error which should be ignored
Instead of this, you could just do:
```
if self.args[name].get("type") is None:
  pass
else:
  # call the method
```

2019-11-20 21:06 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +            except ValueError:          #the typecasting is being done to convert str to respective types but sometimes the entered value is a wrong type which is later raised by the isinstance funct
Yeah, you have 2 different steps responsible for doing type validation, which IMO is inelegant.
Ie - you could drop the next step entirely and just rely on this one, and create the contract that if the "type" method  does not raise a ValueError, then it means that the library user is fine with the returned value.

However, we discussed this, and agreed that it is fine for now, so no-op.

2019-11-20 21:06 UTC, kaustubh-karkare commented on solutions/assignment-1/unittest_CLIparser.py
> +        parser.add_mutually_exclusive_args('local', 'remote')
Much better, so you specify the relationship exactly once.

2019-11-20 21:06 UTC, kaustubh-karkare commented on solutions/assignment-1/CLIparser.py
> +                            raise SimultaneousUsageError(arg, group)
Wait, this is O(n^3) complexity? I think it can be reduced to O(n) time + O(n) space.

2019-12-23 05:49 UTC, closed without merging