solution for assignment 2
kaustubh-karkare/project-omega pull request #65
Opened 2019-10-24 15:34 UTC by drs-11

2019-10-25 06:44 UTC, kaustubh-karkare requested changes
Decent start, but the code is kinda focussed on only the usecase you were trying to solve, and isn't really flexible. You can fix that as you work on implementing part2 of the problem.

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.json
> +    "deps": ["test", "algorithms/sort_bubble", "algorithms/sort_merge", "algorithms/sort_quick"],
See the updated problem statement.
In order to do part3 properly, we want to only link one sorting algorithm at a time with the test.cpp file.

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +            self.watch_run = bool((len(sys.argv) > 2) and (sys.argv[2] == "--watch"))
Don't do this manually. Use the argparse library.

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                    continue
Quoting problem statement:

> Feel free to add support for new attributes in the action data structure.

Because a build automation tool should not make assumptions like this.

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                os.chdir(root)
Pretty sure you don't need to change directory if you use the full path in os.stat

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        build_data = json.load(build_file)
Use something like:
```
with open(path + 'build.json') as file_handle:
  json.load(file_handle)
```

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                    print(output_data)
Never print to stdout directly unless you're debugging, and remember to clean up afterwards.

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        for obj in build_data:
Check out part2 of the problem.

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                    if temp_struct[file_name] != self.dir_struct[file_name]:
Names like `temp_struct` and `dir_struct` aren't useful to figure out what the value is.

See coding instruction 3 [here](https://github.com/kaustubh-karkare/project-omega/blob/master/assignments/README.md).

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        os.chdir(addr)
After going through your code, I don't think you need to be using os.chdir as much as you are using.
In fact, I'd challenge you to modify your code to avoid using it entirely.

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                build_file = open('build.json', 'r')
If you've already read this information once from the files, no need to read it again.

You should store all the information in memory after the first reading.

Create classes to represent actions, and you should also figure out how to represent the graph.

2019-10-25 06:44 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build_test.py
> +        self.assertEqual(self.tool.rule_exe("run", os.getcwd())[-1], "1 2 3 4 5 \n1 2 3 4 5 \n1 2 3 4 5 \n")
* Since this operation will create files in this location, if you're running the "clean" action in parallel, it will interfere. You should make this impossible. Run your tests in a temporary directory if they will modify file structure (see the tempfile module).

2019-10-25 14:43 UTC, drs-11 commented
on it

2019-12-25 19:54 UTC, kaustubh-karkare requested changes

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        self.graph_dict = dict()
graph_dict? It doesn't tell me much about  the contents :(

Based on usage below, lets call this "rule_name_to_rule" ?

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +            if 'build.json' in files:
Store this "build.json" string in some constant and reuse it.

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                with open(root + '/build.json') as build_file:
os.path.join(current_directory, constant)

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                        rule_name = root.partition(self.graph_loc["base_addr"])[-1][1:] + "/" + obj["name"] if root != self.graph_loc["base_addr"] else obj["name"]
This line is hard to understand.

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        for root, dirs, files in os.walk(os.getcwd()):
s/root/current_location/

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                            self.graph_dict[rule_name].command = obj["command"]
You can move this logic to the Rule class, which is responsible for extracting information from a single JSON object. That way, the Graph doesn't need to worry about Rule-level logic.

rule = Rule.create(obj)
self.rule_name_to_rule[rule.name] = rule

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +
In a separate method, you can detect if there are circular dependencies.

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        self.unresolved_deps = list()
Hmm, I don't think we should store the concept of resolved/unresolved at the rule level.
It matters only for executors, so that is the class which can store this information.

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        name_to_process = {dep: subprocess.Popen((self.graph[dep].command), cwd=self.location_map[dep], shell=True) for dep in process_to_execute if self.graph[dep].command}
- I thought the linter would complain about this line being too long to read properly.
- It looks like `process_to_execute` and `name_to_process.keys()` are basically the same, right? So why have both. Instead of maintaining both structures, just maintain one of them.
- The fact that a rule might not have a command requires special handling here. Can you modify your rule class to hide that detail, so that executors do not have to know about it?

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                        self.graph[parent].remDeps(dep)
Yeah, the executor shouldn't be able to modify the graph/rules objects that it depends on, since this state is relevant only to executor.

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        self.location_map = location_map
IMO the location of the rule should be saved in the rule object, not in a separate map outside the graph.

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +            for root, dirs, files in os.walk(os.getcwd()):
Why os.getcwd? I would think that the graph.base_addr is the relevant thing here.

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +    def map_file_command(self, rule):
Who is calling these methods? This codebase is incomplete.

2019-12-25 19:54 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                for file in files:
I thought you were going to only look at the files explicitly listed in the rule, not all of them.

2020-01-05 23:48 UTC, kaustubh-karkare requested changes

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +class Rule():
Minor preference: put this class at the top, so that I can see how Rule is defined before the Graph that uses it.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        self.deps.remove(dep)
You should ideally avoid modifying the rule objects based on executor.
Ie - if executor needs to remove dependencies, it can keep track of that information in its own class, it shouldn't mutate dependencies.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        self.address = None
Why not just call this `self.cwd` for consistency? address is new terminology.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +    def create(self, obj, rule_name, rule_name_to_rule, addr):
```
@classmethod
def create(cls, ...):
    # do whatever you need to
    return cls(...)

# since rule_name_to_rule is a feature of the Graph, not an individual rule,
# the above create method should not be responsible for populating it
rule = Rule.create(json.load(...))
self.rule_name_to_rule[rule.name] = rule

# once all the rules are populated, then add dependents
```

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        self.parents = list()
Lets call these `dependencies` and `dependents`?
A name like `parent` implies children, and the mapping with the above isn't clear.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        self.RULE_FILE = 'build.json'
If this is a constant (ie - because of the all-caps name), it should be outside the constructor.
```
class Graph:
    RULE_FILE = "build.json"

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        self.BASE_ADDR = os.getcwd()
This can be an argument to the graph.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        rule_obj = self.rule_name_to_rule[rule]
To improve the naming here: s/rule/rule_name/ , which allows you to s/rule_obj/rule/

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                self.detect_circular_dependency(dep, resolved, seen)
Can you do this without recursion?

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +    def generate_rule_name(self, addr, rule):
This logic also is specific to a rule, not the entire graph.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +    def exe(self, rule, resolved=[], unresolved=[]):
* See [this issue](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments). Instead of passing it around as an argument, you can just save it on the class: `self.resolved`
* Doesn't look like you're using `unresolved` anyway.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +    def exe(self, rule):
s/rule/rule_name/

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                    stack.append(dep)
You're using it as a queue, not a stack.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                else:
Don't need the `else`. You can avoid one layer of indenting for the following code.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +            for dep in list(name_to_process):
s/dep/rule_name/

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                if name_to_process[dep].poll() is None:
You probably also want to verify that the return value of poll() is 0 if not None.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                            if self.graph[parent].command:
What if this command is None? Shouldn't you trigger more dependents of that rule?

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        if rule in self.file_deps.values():
s/file_deps/filepath_to_rule_name/

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        files = input("Enter depended files for %s(Press Enter if none): " % (rule)).split()
instead of taking this as input, this information should be part of the build.json file.
ie - each rule can be associated with the files it compiles

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +            for root, _, files in os.walk(os.getcwd()): #base addr inaccesible from graph as the dictionary is being taken instead of the whole object, thus os.getcwd is used again
This isn't right. You shouldn't have more than one place in code making assumptions like this, because they can get out of sync.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        while True:
If this is infinite loop that is detecting changes, how can it be in an "init" method?
This logic to set the original modification-times for files is the "init" part of it, yes, but to compare it to new values of mtime is not "init". You should separate the logic into 2 parts.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                                self.executor.exe(parent)
What if the parents also have parents that need to be recompiled?
Assuming only 2 levels isn't right here.

2020-01-05 23:48 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/run_build.py
> +        Executor = build.ParallelExe(BuildGraph.rule_name_to_rule)
s/Executor/executor

The python style guide says that names starting with capital letters are for classes, not class instances.

2020-01-09 14:25 UTC, drs-11 commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        files = input("Enter depended files for %s(Press Enter if none): " % (rule)).split()
but wouldn't having a map between file_name and associated rule be convenient and faster for executing dependent actions?

2020-01-11 18:32 UTC, kaustubh-karkare approved these changes
I think you've now reached a reasonable point on this problem.
You can continue working on it, or we could move on now.

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +    def generate_rule_name(self, base_addr):
This feels like it should be a private method.

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +            rule_obj.command = obj["command"]
This is simpler:
```
rule_obj.dependencies.extend(obj.get("deps", []))
rule_obj.command = obj.get("command")
```
Check out the difference between accessing a key using [] notation vs "get"

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        '''generates the name of the rule with a relative path'''
Instead of the relative path, how about always using absolute paths?

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +            seen = list()
Since the default value is None, you can check for that explicitly.
```
if resolved is None:

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        return False
You don't need to return anything here.
The contract is that if there is a problem, then an exception is raised, otherwise the function completes without problems.

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        self.graph = graph_obj.rule_name_to_rule
Try to use the same name as much as possible.
```
self.rule_name_to_rule = graph_obj.rule_name_to_rule
```
Alternatively, you could even do:
```
self.graph = graph
# later
something(self.graph.rule_name_to_rule)

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                        independent_deps.add(dep)
What if there is only 1 rule in the project?
If the vertex does not have dependencies, you should add it to independent_deps too.

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        process_to_execute = self.get_independent_deps(rule_name)
Inaccurate name.

s/process_to_execute/independent_deps/

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                    process_to_execute.remove(rule_name)
These 2 lines do the same thing?

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                        self.resolved_deps[parent].append(rule_name)
You don't actually need to maintain the list of resolved_deps, since you never use it.

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                                    process_to_execute.add(dependent)
This is never used in the loop.

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                            if self.graph[parent].command:
The current code still does not work.
How about something like:
```
name_to_process[parent] = self.graph[parent].exe_rule()
# even if rule.command is None, since that is handled by the Rule class
```
and on line 110, 
```
if name_to_process[rule_name] is None or name_to_process[rule_name].poll() is not None:
```
to handle both cases

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                for root, _, files in os.walk(self.executor.graph_obj.base_addr):
Typically the term "root" describes the root of the filesystem or the project or something, and generally is fixed.
In this case, "current_directory" is more accurate than root.

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                        self.filepath_to_rule_name[file] = rule
Instead of re-opening the file, why not save the list of files originally while creating the graph?

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +        files = input("Enter depended files for %s(Press Enter if none): " % (rule)).split()
> wouldn't having a map between file_name and associated rule be convenient and faster for executing dependent actions?

It will be, and that is how I did it too, which is fine.

I'm actually saying an unrelated thing: since the source of this information is build.json, we don't need to ask the user for it via this input method. You shouldn't modify that file either, since it is created and therefore owned by the user.

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/build.py
> +                        with open(os.path.join(root, self.executor.graph_obj.RULE_FILE)) as build_file:
There are 2 options here:
* What you've done is to re-fetch all build.json files in each loop, and then look at each file.
* Alternatively, explore `build.json` files only once, since the build rules for a project change very infrequently compared to the rest of the code, and then only look at the files.
Both are fine I guess.

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/unittest_build.py
> +        with tempfile.TemporaryDirectory() as TempDir:
Python style says that variable names are lowercase with underscores, while class names are camel-case.
```
with tempfile.TemporaryDirectory() as temp_dir_name:

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/unittest_build.py
> +            build_tool_graph = build.Graph()
This should work too:
```
graph = build.Graph(temp_dir_name)
```
That way, you don't ever need to call `os.chdir`

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/unittest_build.py
> +            files = ["test.o","algorithms/sort_merge.o", "algorithms/sort_bubble.o", "algorithms/sort_quick.o", "test_sort_bubble.exe", "test_sort_quick.exe", "test_sort_merge.exe"]
Why are the rest of these things being built if the only rule being executed is `test_sort_merge`?

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/unittest_build.py
> +            for file in files:
Instead of a long line, this is more readable:
```
for file_name in [
  "test.o",
  ...
]
```
Also note the better name. "file" can refer to the file handle or the name, so always prefer being more specific.

2020-01-11 18:32 UTC, kaustubh-karkare commented on solutions/d-r-siddhartha/assignment-2/unittest_build.py
> +    def test_parallel_build(self):
This test doesn't really prove that things happen in parallel, right?
Ie - if you used the SerialExecutor was used, it would still work.
How can you modify it so that SerialExecutor would fail, but ParallelExecutor would pass?

2020-02-19 17:59 UTC, closed without merging